# Generated by Django 4.2.11 on 2024-04-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bincol_pro', '0002_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_number', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(choices=[('NSW', 'New South Wales'), ('VIC', 'Victoria'), ('QLD', 'Queensland')], max_length=3)),
                ('capacity', models.IntegerField(choices=[(100, '100 litres'), (200, '200 litres'), (300, '300 litres')])),
                ('status', models.CharField(choices=[('Emptied', 'Emptied'), ('Filled', 'Filled')], max_length=20)),
            ],
        ),
    ]
