# Generated by Django 4.2.11 on 2024-04-16 20:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bincol_pro', '0006_alter_complaint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
