# Generated by Django 4.2.11 on 2024-04-18 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bincol_pro', '0007_bin_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='status',
            field=models.CharField(choices=[('Emptied', 'Emptied'), ('Filled', 'Filled')], default='Filled', max_length=20),
        ),
        migrations.CreateModel(
            name='BinEmptyingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emptied_at', models.DateTimeField(auto_now_add=True)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bincol_pro.bin')),
                ('emptied_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
